UI Migration for Journey's and QuickChat
the-answerai/theanswer pull request #24
Opened 2024-08-05 16:57 UTC by bradtaylorsf

2024-08-06 13:52 UTC, maxtechera requested changes
The changes look good overall. Please cleanup the console logs that you used during development. Thanks.

2024-08-06 13:52 UTC, maxtechera commented on packages/server/src/middlewares/authentication/index.ts
> +    authRequired: true,
What's the purpose of this change?

2024-08-06 13:52 UTC, maxtechera commented on packages/ui/src/views/agentflows/index.jsx
> +    const renderItemCard = ({ item, images, nodeTypes, onClick, type, updateFlowsApi, setError }) => (
This function is defined on every render, will produce unnecessary re-renders and can hurt performance heavily.

2025-03-06 16:29 UTC, spindle79 commented
Reminder to @bradtaylorsf Keep multi-document support and overriding the tools

2025-07-09 00:11 UTC, closed without merging