added embeded apps setting
the-answerai/theanswer pull request #42
Opened 2024-10-07 02:41 UTC by bradtaylorsf

2024-10-07 16:40 UTC, maxtechera requested changes

2024-10-07 16:40 UTC, maxtechera commented on packages-answers/ui/src/ChatDetail.tsx
> -                                            <MessageCard id='error' role='assistant' content={`${error.message} `} error={error} />
Not sure if we have support for this role as it's not openai valid

2024-10-07 16:40 UTC, maxtechera commented on packages/docs/docs/using-answerai/sidekick-studio/sidekick-settings/general.md
🙌

2024-10-07 16:40 UTC, maxtechera commented on packages/server/src/services/chatflows/index.ts
> +
why is this parse/unparse needed?

2024-10-08 01:38 UTC, bradtaylorsf commented on packages/server/src/services/chatflows/index.ts
> +
The parse/unparse operation in the updateChatflow function is needed for a few reasons:

1. Type safety: The chatbotConfig is stored as a string in the database, but we need to work with it as an object in our code. Parsing it allows us to manipulate it as a JavaScript object.
2. Partial updates: The function allows for partial updates of the chatbotConfig. By parsing the existing config and the new config separately, we can selectively update only the fields that are provided in the new config.
3. Maintaining existing data: By parsing the existing chatbotConfig, we ensure that we don't lose any existing configuration data that isn't being updated in this operation.

2024-10-08 14:49 UTC, merged